[2025-03-19T07:31:02.072+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract scheduled__2025-03-19T06:10:00+00:00 [queued]>
[2025-03-19T07:31:02.077+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract scheduled__2025-03-19T06:10:00+00:00 [queued]>
[2025-03-19T07:31:02.078+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-19T07:31:02.088+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2025-03-19 06:10:00+00:00
[2025-03-19T07:31:02.091+0000] {standard_task_runner.py:57} INFO - Started process 224 to run task
[2025-03-19T07:31:02.093+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'scheduled__2025-03-19T06:10:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmp19c8hlcd']
[2025-03-19T07:31:02.094+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask extract
[2025-03-19T07:31:02.106+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-19T07:31:02.133+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_pipeline.extract scheduled__2025-03-19T06:10:00+00:00 [running]> on host 7b70899a1576
[2025-03-19T07:31:02.182+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T06:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-19T06:10:00+00:00'
[2025-03-19T07:31:02.184+0000] {logging_mixin.py:154} INFO - Loading file from: /opt/airflow/dags/scripts/districts.json
[2025-03-19T07:31:18.303+0000] {logging_mixin.py:154} INFO - Saved data for Quan 1
[2025-03-19T07:31:30.921+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-03-19T07:31:30.922+0000] {process_utils.py:131} INFO - Sending 15 to group 224. PIDs of all processes in the group: [224]
[2025-03-19T07:31:30.922+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 224
[2025-03-19T07:31:30.923+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-19T07:31:30.929+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/extract.py", line 36, in extract_data
    time.sleep(15)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-03-19T07:31:30.937+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=extract, execution_date=20250319T061000, start_date=20250319T073102, end_date=20250319T073130
[2025-03-19T07:31:30.945+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 65 for task extract (Task received SIGTERM signal; 224)
[2025-03-19T07:31:30.949+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=224, status='terminated', exitcode=1, started='07:31:01') (224) terminated with exit code 1
[2025-03-19T07:31:30.950+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2025-03-19T07:31:30.966+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T07:48:42.058+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract scheduled__2025-03-19T06:10:00+00:00 [queued]>
[2025-03-19T07:48:42.064+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract scheduled__2025-03-19T06:10:00+00:00 [queued]>
[2025-03-19T07:48:42.065+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-19T07:48:42.073+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2025-03-19 06:10:00+00:00
[2025-03-19T07:48:42.076+0000] {standard_task_runner.py:57} INFO - Started process 107 to run task
[2025-03-19T07:48:42.079+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'scheduled__2025-03-19T06:10:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmp8lzlp_ws']
[2025-03-19T07:48:42.080+0000] {standard_task_runner.py:85} INFO - Job 77: Subtask extract
[2025-03-19T07:48:42.092+0000] {logging_mixin.py:154} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-19T07:48:42.118+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_pipeline.extract scheduled__2025-03-19T06:10:00+00:00 [running]> on host 9431682cb7a1
[2025-03-19T07:48:42.167+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T06:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-19T06:10:00+00:00'
[2025-03-19T07:48:42.170+0000] {logging_mixin.py:154} INFO - Loading file from: /opt/airflow/dags/scripts/districts.json
[2025-03-19T07:48:58.630+0000] {logging_mixin.py:154} INFO - Saved data for Quan 1
[2025-03-19T07:49:14.655+0000] {logging_mixin.py:154} INFO - Saved data for Quan 2
[2025-03-19T07:49:30.684+0000] {logging_mixin.py:154} INFO - Saved data for Quan 3
[2025-03-19T07:49:46.864+0000] {logging_mixin.py:154} INFO - Saved data for TP Thu Duc
[2025-03-19T07:50:02.958+0000] {logging_mixin.py:154} INFO - Saved data for TP Di An
[2025-03-19T07:50:19.402+0000] {logging_mixin.py:154} INFO - Saved data for TP Long Khanh
[2025-03-19T07:50:35.638+0000] {logging_mixin.py:154} INFO - Saved data for TT Phu My
[2025-03-19T07:50:51.641+0000] {logging_mixin.py:154} INFO - Saved data for TP Ba Ria
[2025-03-19T07:50:51.654+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-03-19T07:50:51.662+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract, execution_date=20250319T061000, start_date=20250319T074842, end_date=20250319T075051
[2025-03-19T07:50:51.682+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-19T07:50:51.702+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
